### ISSUE TITLE
API design-의빈님

### ISSUE THREAD

**Issue by SoobinJung1013** [team-e-techeer/teame-docs#15]
# 목적
API spec 설계

# API 작성 참고 자료 
- [API 예제 문서 양식 by Irene Ros](https://gist.github.com/iros/3426278#file-example-md)
- [Notion + Markdown으로 간단한 API Docs 작성하기](https://velog.io/@hdyang0686/NotionMarkdown-%EC%9C%BC%EB%A1%9C-%EA%B0%84%EB%8B%A8%ED%95%9C-API-Docs-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0)

#  작업 상세 내용
- [x]  team-e 노션 -> 문서 -> 구현 기능 리스트 확인
- [x]  team-e 노션 -> 문서 -> API spec 예시 확인
- [x] API 스펙 설계해보기

**Comment by JoeCP17** [comment]
https://team-e2.notion.site/API-spec-55d1835d921549cba367eadcd8e0eb99
